go:
  output-folder: Client
  namespace: foo
output-folder: Artifacts
title: Azure DevOps SDK
input-file:
  - ./core-5.1-modified.json
  # - https://github.com/MicrosoftDocs/vsts-rest-api-specs/blob/master/specification/account/4.1/accounts.json
  # - https://github.com/MicrosoftDocs/vsts-rest-api-specs/blob/master/specification/account/5.0/accounts.json
  # - https://github.com/MicrosoftDocs/vsts-rest-api-specs/blob/master/specification/account/5.1/accounts.json
  # - https://github.com/MicrosoftDocs/vsts-rest-api-specs/blob/master/specification/artifacts/5.0/feed.json
  # - https://github.com/MicrosoftDocs/vsts-rest-api-specs/blob/master/specification/artifacts/5.0/provenance.json
  # - https://github.com/MicrosoftDocs/vsts-rest-api-specs/blob/master/specification/artifacts/5.1/feed.json
  # - https://github.com/MicrosoftDocs/vsts-rest-api-specs/blob/master/specification/artifacts/5.1/provenance.json
  # - https://github.com/MicrosoftDocs/vsts-rest-api-specs/blob/master/specification/artifacts/azure-devops-server-5.0/feed-onprem.json
  # - https://github.com/MicrosoftDocs/vsts-rest-api-specs/blob/master/specification/artifactsPackageTypes/5.0/maven.json
  # - https://github.com/MicrosoftDocs/vsts-rest-api-specs/blob/master/specification/artifactsPackageTypes/5.0/npm.json
  # - https://github.com/MicrosoftDocs/vsts-rest-api-specs/blob/master/specification/artifactsPackageTypes/5.0/nuGet.json
  # - https://github.com/MicrosoftDocs/vsts-rest-api-specs/blob/master/specification/artifactsPackageTypes/5.0/pyPiApi.json
  # - https://github.com/MicrosoftDocs/vsts-rest-api-specs/blob/master/specification/artifactsPackageTypes/5.0/universal.json
  # - https://github.com/MicrosoftDocs/vsts-rest-api-specs/blob/master/specification/artifactsPackageTypes/5.1/maven.json
  # - https://github.com/MicrosoftDocs/vsts-rest-api-specs/blob/master/specification/artifactsPackageTypes/5.1/npm.json
  # - https://github.com/MicrosoftDocs/vsts-rest-api-specs/blob/master/specification/artifactsPackageTypes/5.1/nuGet.json
  # - https://github.com/MicrosoftDocs/vsts-rest-api-specs/blob/master/specification/artifactsPackageTypes/5.1/pyPiApi.json
  # - https://github.com/MicrosoftDocs/vsts-rest-api-specs/blob/master/specification/artifactsPackageTypes/5.1/universal.json
  # - https://github.com/MicrosoftDocs/vsts-rest-api-specs/blob/master/specification/artifactsPackageTypes/azure-devops-server-5.0/maven-onprem.json
  # - https://github.com/MicrosoftDocs/vsts-rest-api-specs/blob/master/specification/artifactsPackageTypes/azure-devops-server-5.0/npm-onprem.json
  # - https://github.com/MicrosoftDocs/vsts-rest-api-specs/blob/master/specification/artifactsPackageTypes/azure-devops-server-5.0/nuGet-onprem.json
  # - https://github.com/MicrosoftDocs/vsts-rest-api-specs/blob/master/specification/audit/5.1/audit.json
  # - https://github.com/MicrosoftDocs/vsts-rest-api-specs/blob/master/specification/build/4.1/build.json
  # - https://github.com/MicrosoftDocs/vsts-rest-api-specs/blob/master/specification/build/5.0/build.json
  # - https://github.com/MicrosoftDocs/vsts-rest-api-specs/blob/master/specification/build/5.1/build.json
  # - https://github.com/MicrosoftDocs/vsts-rest-api-specs/blob/master/specification/build/azure-devops-server-5.0/build-onprem.json
  # - https://github.com/MicrosoftDocs/vsts-rest-api-specs/blob/master/specification/build/tfs-4.1/build-onprem.json
  # - https://github.com/MicrosoftDocs/vsts-rest-api-specs/blob/master/specification/clt/4.1/cloudLoadTest.json
  # - https://github.com/MicrosoftDocs/vsts-rest-api-specs/blob/master/specification/clt/5.0/cloudLoadTest.json
  # - https://github.com/MicrosoftDocs/vsts-rest-api-specs/blob/master/specification/clt/5.1/cloudLoadTest.json
  # - https://github.com/MicrosoftDocs/vsts-rest-api-specs/blob/master/specification/core/4.1/core.json
  # - https://github.com/MicrosoftDocs/vsts-rest-api-specs/blob/master/specification/core/5.0/core.json
  # - https://github.com/MicrosoftDocs/vsts-rest-api-specs/blob/master/specification/core/5.1/core.json
  # - https://github.com/MicrosoftDocs/vsts-rest-api-specs/blob/master/specification/core/azure-devops-server-5.0/core-onprem.json
  # - https://github.com/MicrosoftDocs/vsts-rest-api-specs/blob/master/specification/core/tfs-4.1/core-onprem.json
  # - https://github.com/MicrosoftDocs/vsts-rest-api-specs/blob/master/specification/dashboard/4.1/dashboard.json
  # - https://github.com/MicrosoftDocs/vsts-rest-api-specs/blob/master/specification/dashboard/5.0/dashboard.json
  # - https://github.com/MicrosoftDocs/vsts-rest-api-specs/blob/master/specification/dashboard/5.1/dashboard.json
  # - https://github.com/MicrosoftDocs/vsts-rest-api-specs/blob/master/specification/dashboard/azure-devops-server-5.0/dashboard-onprem.json
  # - https://github.com/MicrosoftDocs/vsts-rest-api-specs/blob/master/specification/dashboard/tfs-4.1/dashboard-onprem.json
  # - https://github.com/MicrosoftDocs/vsts-rest-api-specs/blob/master/specification/distributedTask/4.1/taskAgent.json
  # - https://github.com/MicrosoftDocs/vsts-rest-api-specs/blob/master/specification/distributedTask/5.0/taskAgent.json
  # - https://github.com/MicrosoftDocs/vsts-rest-api-specs/blob/master/specification/distributedTask/5.1/taskAgent.json
  # - https://github.com/MicrosoftDocs/vsts-rest-api-specs/blob/master/specification/distributedTask/azure-devops-server-5.0/taskAgent-onprem.json
  # - https://github.com/MicrosoftDocs/vsts-rest-api-specs/blob/master/specification/distributedTask/tfs-4.1/taskAgent-onprem.json
  # - https://github.com/MicrosoftDocs/vsts-rest-api-specs/blob/master/specification/extensionManagement/4.1/extensionManagement.json
  # - https://github.com/MicrosoftDocs/vsts-rest-api-specs/blob/master/specification/extensionManagement/5.0/extensionManagement.json
  # - https://github.com/MicrosoftDocs/vsts-rest-api-specs/blob/master/specification/extensionManagement/5.1/extensionManagement.json
  # - https://github.com/MicrosoftDocs/vsts-rest-api-specs/blob/master/specification/extensionManagement/azure-devops-server-5.0/extensionManagement-onprem.json
  # - https://github.com/MicrosoftDocs/vsts-rest-api-specs/blob/master/specification/extensionManagement/tfs-4.1/extensionManagement-onprem.json
  # - https://github.com/MicrosoftDocs/vsts-rest-api-specs/blob/master/specification/git/4.1/git.json
  # - https://github.com/MicrosoftDocs/vsts-rest-api-specs/blob/master/specification/git/5.0/git.json
  # - https://github.com/MicrosoftDocs/vsts-rest-api-specs/blob/master/specification/git/5.1/git.json
  # - https://github.com/MicrosoftDocs/vsts-rest-api-specs/blob/master/specification/git/azure-devops-server-5.0/git-onprem.json
  # - https://github.com/MicrosoftDocs/vsts-rest-api-specs/blob/master/specification/git/tfs-4.1/git-onprem.json
  # - https://github.com/MicrosoftDocs/vsts-rest-api-specs/blob/master/specification/graph/4.1/graph.json
  # - https://github.com/MicrosoftDocs/vsts-rest-api-specs/blob/master/specification/graph/5.0/graph.json
  # - https://github.com/MicrosoftDocs/vsts-rest-api-specs/blob/master/specification/graph/5.1/graph.json
  # - https://github.com/MicrosoftDocs/vsts-rest-api-specs/blob/master/specification/hooks/4.1/serviceHooks.json
  # - https://github.com/MicrosoftDocs/vsts-rest-api-specs/blob/master/specification/hooks/5.0/serviceHooks.json
  # - https://github.com/MicrosoftDocs/vsts-rest-api-specs/blob/master/specification/hooks/5.1/serviceHooks.json
  # - https://github.com/MicrosoftDocs/vsts-rest-api-specs/blob/master/specification/hooks/azure-devops-server-5.0/serviceHooks-onprem.json
  # - https://github.com/MicrosoftDocs/vsts-rest-api-specs/blob/master/specification/hooks/tfs-4.1/serviceHooks-onprem.json
  # - https://github.com/MicrosoftDocs/vsts-rest-api-specs/blob/master/specification/memberEntitlementManagement/4.1/memberEntitlementManagement.json
  # - https://github.com/MicrosoftDocs/vsts-rest-api-specs/blob/master/specification/memberEntitlementManagement/5.0/memberEntitlementManagement.json
  # - https://github.com/MicrosoftDocs/vsts-rest-api-specs/blob/master/specification/memberEntitlementManagement/5.1/memberEntitlementManagement.json
  # - https://github.com/MicrosoftDocs/vsts-rest-api-specs/blob/master/specification/notification/4.1/notification.json
  # - https://github.com/MicrosoftDocs/vsts-rest-api-specs/blob/master/specification/notification/5.0/notification.json
  # - https://github.com/MicrosoftDocs/vsts-rest-api-specs/blob/master/specification/notification/5.1/notification.json
  # - https://github.com/MicrosoftDocs/vsts-rest-api-specs/blob/master/specification/notification/azure-devops-server-5.0/notification-onprem.json
  # - https://github.com/MicrosoftDocs/vsts-rest-api-specs/blob/master/specification/notification/tfs-4.1/notification-onprem.json
  # - https://github.com/MicrosoftDocs/vsts-rest-api-specs/blob/master/specification/operations/4.1/operations.json
  # - https://github.com/MicrosoftDocs/vsts-rest-api-specs/blob/master/specification/operations/5.0/operations.json
  # - https://github.com/MicrosoftDocs/vsts-rest-api-specs/blob/master/specification/operations/5.1/operations.json
  # - https://github.com/MicrosoftDocs/vsts-rest-api-specs/blob/master/specification/operations/azure-devops-server-5.0/operations-onprem.json
  # - https://github.com/MicrosoftDocs/vsts-rest-api-specs/blob/master/specification/operations/tfs-4.1/operations-onprem.json
  # - https://github.com/MicrosoftDocs/vsts-rest-api-specs/blob/master/specification/policy/4.1/policy.json
  # - https://github.com/MicrosoftDocs/vsts-rest-api-specs/blob/master/specification/policy/5.0/policy.json
  # - https://github.com/MicrosoftDocs/vsts-rest-api-specs/blob/master/specification/policy/5.1/policy.json
  # - https://github.com/MicrosoftDocs/vsts-rest-api-specs/blob/master/specification/policy/azure-devops-server-5.0/policy-onprem.json
  # - https://github.com/MicrosoftDocs/vsts-rest-api-specs/blob/master/specification/policy/tfs-4.1/policy-onprem.json
  # - https://github.com/MicrosoftDocs/vsts-rest-api-specs/blob/master/specification/processadmin/4.1/workItemTrackingProcessTemplate.json
  # - https://github.com/MicrosoftDocs/vsts-rest-api-specs/blob/master/specification/processadmin/5.0/workItemTrackingProcessTemplate.json
  # - https://github.com/MicrosoftDocs/vsts-rest-api-specs/blob/master/specification/processadmin/5.1/workItemTrackingProcessTemplate.json
  # - https://github.com/MicrosoftDocs/vsts-rest-api-specs/blob/master/specification/processadmin/azure-devops-server-5.0/workItemTrackingProcessTemplate-onprem.json
  # - https://github.com/MicrosoftDocs/vsts-rest-api-specs/blob/master/specification/processadmin/tfs-4.1/workItemTrackingProcessTemplate-onprem.json
  # - https://github.com/MicrosoftDocs/vsts-rest-api-specs/blob/master/specification/processDefinitions/4.1/workItemTrackingProcessDefinitions.json
  # - https://github.com/MicrosoftDocs/vsts-rest-api-specs/blob/master/specification/processDefinitions/tfs-4.1/workItemTrackingProcessDefinitions-onprem.json
  # - https://github.com/MicrosoftDocs/vsts-rest-api-specs/blob/master/specification/processes/4.1/workItemTrackingProcess.json
  # - https://github.com/MicrosoftDocs/vsts-rest-api-specs/blob/master/specification/processes/5.0/workItemTrackingProcess.json
  # - https://github.com/MicrosoftDocs/vsts-rest-api-specs/blob/master/specification/processes/5.1/workItemTrackingProcess.json
  # - https://github.com/MicrosoftDocs/vsts-rest-api-specs/blob/master/specification/processes/azure-devops-server-5.0/workItemTrackingProcess-onprem.json
  # - https://github.com/MicrosoftDocs/vsts-rest-api-specs/blob/master/specification/processes/tfs-4.1/workItemTrackingProcess-onprem.json
  # - https://github.com/MicrosoftDocs/vsts-rest-api-specs/blob/master/specification/profile/4.1/profile.json
  # - https://github.com/MicrosoftDocs/vsts-rest-api-specs/blob/master/specification/profile/5.0/profile.json
  # - https://github.com/MicrosoftDocs/vsts-rest-api-specs/blob/master/specification/profile/5.1/profile.json
  # - https://github.com/MicrosoftDocs/vsts-rest-api-specs/blob/master/specification/release/4.1/release.json
  # - https://github.com/MicrosoftDocs/vsts-rest-api-specs/blob/master/specification/release/5.0/release.json
  # - https://github.com/MicrosoftDocs/vsts-rest-api-specs/blob/master/specification/release/5.1/release.json
  # - https://github.com/MicrosoftDocs/vsts-rest-api-specs/blob/master/specification/release/azure-devops-server-5.0/release-onprem.json
  # - https://github.com/MicrosoftDocs/vsts-rest-api-specs/blob/master/specification/release/tfs-4.1/release-onprem.json
  # - https://github.com/MicrosoftDocs/vsts-rest-api-specs/blob/master/specification/search/4.1/search.json
  # - https://github.com/MicrosoftDocs/vsts-rest-api-specs/blob/master/specification/search/5.0/search.json
  # - https://github.com/MicrosoftDocs/vsts-rest-api-specs/blob/master/specification/search/5.1/search.json
  # - https://github.com/MicrosoftDocs/vsts-rest-api-specs/blob/master/specification/search/azure-devops-server-5.0/search-onprem.json
  # - https://github.com/MicrosoftDocs/vsts-rest-api-specs/blob/master/specification/search/tfs-4.1/search-onprem.json
  # - https://github.com/MicrosoftDocs/vsts-rest-api-specs/blob/master/specification/security/4.1/security.json
  # - https://github.com/MicrosoftDocs/vsts-rest-api-specs/blob/master/specification/security/5.0/security.json
  # - https://github.com/MicrosoftDocs/vsts-rest-api-specs/blob/master/specification/security/5.1/security.json
  # - https://github.com/MicrosoftDocs/vsts-rest-api-specs/blob/master/specification/security/azure-devops-server-5.0/security-onprem.json
  # - https://github.com/MicrosoftDocs/vsts-rest-api-specs/blob/master/specification/security/tfs-4.1/security-onprem.json
  # - https://github.com/MicrosoftDocs/vsts-rest-api-specs/blob/master/specification/serviceEndpoint/4.1/serviceEndpoint.json
  # - https://github.com/MicrosoftDocs/vsts-rest-api-specs/blob/master/specification/serviceEndpoint/5.0/serviceEndpoint.json
  # - https://github.com/MicrosoftDocs/vsts-rest-api-specs/blob/master/specification/serviceEndpoint/5.1/serviceEndpoint.json
  # - https://github.com/MicrosoftDocs/vsts-rest-api-specs/blob/master/specification/serviceEndpoint/azure-devops-server-5.0/serviceEndpoint-onprem.json
  # - https://github.com/MicrosoftDocs/vsts-rest-api-specs/blob/master/specification/serviceEndpoint/tfs-4.1/serviceEndpoint-onprem.json
  # - https://github.com/MicrosoftDocs/vsts-rest-api-specs/blob/master/specification/symbol/4.1/symbol.json
  # - https://github.com/MicrosoftDocs/vsts-rest-api-specs/blob/master/specification/symbol/5.0/symbol.json
  # - https://github.com/MicrosoftDocs/vsts-rest-api-specs/blob/master/specification/symbol/5.1/symbol.json
  # - https://github.com/MicrosoftDocs/vsts-rest-api-specs/blob/master/specification/test/5.0/test.json
  # - https://github.com/MicrosoftDocs/vsts-rest-api-specs/blob/master/specification/test/5.1/test.json
  # - https://github.com/MicrosoftDocs/vsts-rest-api-specs/blob/master/specification/test/azure-devops-server-5.0/test-onprem.json
  # - https://github.com/MicrosoftDocs/vsts-rest-api-specs/blob/master/specification/testPlan/5.0/testPlan.json
  # - https://github.com/MicrosoftDocs/vsts-rest-api-specs/blob/master/specification/testPlan/5.1/testPlan.json
  # - https://github.com/MicrosoftDocs/vsts-rest-api-specs/blob/master/specification/testPlan/azure-devops-server-5.0/testPlan-onprem.json
  # - https://github.com/MicrosoftDocs/vsts-rest-api-specs/blob/master/specification/tfvc/4.1/tfvc.json
  # - https://github.com/MicrosoftDocs/vsts-rest-api-specs/blob/master/specification/tfvc/5.0/tfvc.json
  # - https://github.com/MicrosoftDocs/vsts-rest-api-specs/blob/master/specification/tfvc/5.1/tfvc.json
  # - https://github.com/MicrosoftDocs/vsts-rest-api-specs/blob/master/specification/tfvc/azure-devops-server-5.0/tfvc-onprem.json
  # - https://github.com/MicrosoftDocs/vsts-rest-api-specs/blob/master/specification/tfvc/tfs-4.1/tfvc-onprem.json
  # - https://github.com/MicrosoftDocs/vsts-rest-api-specs/blob/master/specification/tokenAdmin/5.0/tokenAdmin.json
  # - https://github.com/MicrosoftDocs/vsts-rest-api-specs/blob/master/specification/tokenAdmin/5.1/tokenAdmin.json
  # - https://github.com/MicrosoftDocs/vsts-rest-api-specs/blob/master/specification/tokenAdmin/azure-devops-server-5.0/tokenAdmin-onprem.json
  # - https://github.com/MicrosoftDocs/vsts-rest-api-specs/blob/master/specification/tokenAdministration/5.0/tokenAdministration.json
  # - https://github.com/MicrosoftDocs/vsts-rest-api-specs/blob/master/specification/tokenAdministration/5.1/tokenAdministration.json
  # - https://github.com/MicrosoftDocs/vsts-rest-api-specs/blob/master/specification/wiki/4.1/wiki.json
  # - https://github.com/MicrosoftDocs/vsts-rest-api-specs/blob/master/specification/wiki/5.0/wiki.json
  # - https://github.com/MicrosoftDocs/vsts-rest-api-specs/blob/master/specification/wiki/5.1/wiki.json
  # - https://github.com/MicrosoftDocs/vsts-rest-api-specs/blob/master/specification/wiki/azure-devops-server-5.0/wiki-onprem.json
  # - https://github.com/MicrosoftDocs/vsts-rest-api-specs/blob/master/specification/wiki/tfs-4.1/wiki-onprem.json
  # - https://github.com/MicrosoftDocs/vsts-rest-api-specs/blob/master/specification/wit/4.1/workItemTracking.json
  # - https://github.com/MicrosoftDocs/vsts-rest-api-specs/blob/master/specification/wit/5.0/workItemTracking.json
  # - https://github.com/MicrosoftDocs/vsts-rest-api-specs/blob/master/specification/wit/5.1/workItemTracking.json
  # - https://github.com/MicrosoftDocs/vsts-rest-api-specs/blob/master/specification/wit/azure-devops-server-5.0/workItemTracking-onprem.json
  # - https://github.com/MicrosoftDocs/vsts-rest-api-specs/blob/master/specification/wit/tfs-4.1/workItemTracking-onprem.json
  # - https://github.com/MicrosoftDocs/vsts-rest-api-specs/blob/master/specification/work/4.1/work.json
  # - https://github.com/MicrosoftDocs/vsts-rest-api-specs/blob/master/specification/work/5.0/work.json
  # - https://github.com/MicrosoftDocs/vsts-rest-api-specs/blob/master/specification/work/5.1/work.json
  # - https://github.com/MicrosoftDocs/vsts-rest-api-specs/blob/master/specification/work/azure-devops-server-5.0/work-onprem.json
  # - https://github.com/MicrosoftDocs/vsts-rest-api-specs/blob/master/specification/work/tfs-4.1/work-onprem.json