# This is an example goreleaser.yaml file with some sane defaults.
builds:
- binary: "{{ .ProjectName }}_{{ .Tag }}"
  env:
  - CGO_ENABLED=0
  goos:
  - linux
  - windows
  - darwin
archives:
- name_template: "{{ .ProjectName }}_{{ .Tag }}_{{ .Os }}_{{ .Arch }}"
  format_overrides:
    - goos: windows
      format: zip
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "ni-azuredevops"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
release:
  github:
    owner: ni
    name: terraform-provider-azuredevops-ni
